### ISSUE TITLE
resolve repetitive fixture pathing in test fixtures

### ISSUE THREAD

**Issue by glnster** [babel-plugin-ember-test-metadata/babel-plugin-ember-test-metadata#7]
We have a lot of repetitive fixture pathing across the tests. E.g. Lines like this:
`'__tests__/__fixtures__/multiple-module-no-beforeeach-import-exists-code.js';`
across output fixtures.

It would be nice to abstract this out to perhaps a getFixture util, that takes in the filename and returns it, to resolve/automate pathing.

**Comment by drewlee** [comment]
This has been addressed with the `getTestFiles` util function.
